graph TD;
    "enroll.html" --> "style.css";
    "enroll.html" --> "script.js";
    "mentors.html" --> "style.css";
    "mentors.html" --> "script.js";
    "index.html" --> "style.css";
    "index.html" --> "script.js";
